### PR TITLE
#39: Add color to varify deps status results

### PR DESCRIPTION
**Pull request by rffrancon**

### CODE REVIEW

**Comment by dpc** [comment]
Concept OK, but colored won't work on windows. Also, it will print ascii garbage when users pipe the outputs to file etc.

We should use `term` crate, which is much more pain to use, because it can't abstract thing away as Strings, but that's because on windows colors are drawn by calling some functions etc.

You can use https://github.com/slog-rs/term/blob/master/src/lib.rs#L1380 as a reference on how to use `term`.

You should probably implement something like this:

```
impl VerificationStatus {
 fn write_colored_to_stdout(&self) -> io::Result<()> { ... }
 fn write_colored_to_stderr(&self) -> io::Result<()> { ... }
}
```

**Comment by rffrancon** [comment]
Thanks for the feedback! I'll take a look at term.

**Comment by rffrancon** [comment]
@dpc Is this the sort of thing you were thinking of?
I've used `term.supports_color()`. Do you think that I need to query `isatty` from libc also?

**Comment by dpc** [comment]
I have landed (that's my philosophy), but there are problems:


See `cargo crev verify deps | less`. The output is corrupted because we need to use something like https://docs.rs/atty/0.2.11/atty/ to detect if the output is actually an interactive terminal that supports colors. `term.supports_color()` must be  checking something else. I'm guessing if`$TERM` variable supports color?

Some other improvements:

There will be more stuff to output in color.

We should probably have an API like this:

trait Colorizable {
   fn color(&self) -> SomeTypeForColor;
}
```

and then some generic function/struct that checks `term.supports_color()` and `atty` and given an argument of type `T : Colorizable + Display` outputs it on `stderr` or `stdout`. The checks should probably be cached (I'm not sure how expensive they are).

@rffrancon Thank you for this PR, and let me know if you plan to work on the above, or should I look into it eventually, when I find a time.

**Comment by dpc** [comment]
I'm going to take a quick stab at it.

**Comment by rffrancon** [comment]
@dpc Thank you for the feedback once more! I see that you've pushed this much further than what I had in mind, looks great. :)

**Pull request merged**
