### PR TITLE
Move from `app_dirs` to `directories`.

### LINKED ISSUE #125: Windows paths could be improved.
Currently on Windows the paths used by crev look like this: `X:\Users\<Username>\AppData\Local\Dawid Ci,281,,380,arkiewicz\crev\remotes`.

My proposition is to remove the `Dawid Ci,281,,380,arkiewicz` part entirely.
Going to make a PR for it.

### PR DESCRIPTION
**Pull request by daxpedda**
As `app_dirs` is not maintained anymore (see https://github.com/AndyBarron/app-dirs-rs) and as seen [here](https://github.com/dpc/crev/issues/125) there are some issues with config and cache paths on Windows, we should move to a more maintained alternative.

I would like to propose [`directories`](https://crates.io/crates/directories) which is still actively developed.

This has the following effects:
- On Windows `Dawid Ci,281,,380,arkiewicz` will change to `Dawid Ciężarkiewic`.
- On MacOS `Application Support/crev` will change to `Preferences/dev.Dawid-Ciężarkiewic.crev`.

I did not test it on MacOS, it would be appreciated if somebody did.

Also I removed `APP_INFO` completly, is a global similar to it needed?

Fixes #125.

### CODE REVIEW

**Comment by dpc** [comment]
> As app_dirs is not maintained anymore

I should issue a negative proof review then! :D

**Comment by dpc** [comment]
Could we maybe get rid of `Dawid Ciężarkiewicz` altogether? I think we should change it to something more generic. I am not planing to be the sole owner or anything like this.

**Comment by daxpedda** [comment]
> > As app_dirs is not maintained anymore
> 
> I should issue a negative proof review then! :D

I like.

> Could we maybe get rid of `Dawid Ciężarkiewicz` altogether? I think we should change it to something more generic. I am not planing to be the sole owner or anything like this.

I removed it altogether for now.

**Comment by dpc** [comment]
Do you think you could create a short wiki page for people who will upgrade, so they can easily fix their setup?

Maybe we should start maintaining CHANGELOG.md ...

**Comment by dpc** [comment]
https://github.com/dpc/crev-proofs/blob/master/8iUv_SPgsAQ4paabLfs1D9tIptMnuSRZ344_M-6m9RE/reviews/2019-01-packages.proof.crev#L23

**Comment by daxpedda** [comment]
> Do you think you could create a short wiki page for people who will upgrade, so they can easily fix their setup?
> 
> Maybe we should start maintaining CHANGELOG.md ...

Personally I think a `CHANGELOG.md` would be better.
Would like to propose something like that:
- https://keepachangelog.com/en/1.0.0/
- https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

If we start one, I will make a PR to add something about this.

**Comment by dpc** [comment]
@daxpedda Agreed!

**Pull request merged**
