### PR TITLE
Parallelize part of verify deps

### PR DESCRIPTION
**Pull request by Canop**
Result first: it goes from 13s to 5s for the whole program execution on the crev repository.

```
time cargo crev verify deps
real	0m13,009s
user	0m13,105s
sys	0m0,752s

time ../target/release/cargo-crev crev verify deps
real	0m5,069s
user	0m13,192s
sys	0m0,739s

```
Most of the gain comes from executing in parallel the geiger counts.

This PR brings also a big refactoring to separate the verification process from its display (one of the goals being to then improve the display)

### CODE REVIEW

**Comment by dpc** [comment]
How come there are conflicts here in files I haven't touched? :confused:

**Comment by Canop** [comment]
It looks like I messed something with git... I somehow auto-conflicted...

**Comment by dpc** [comment]
I did modify `Cargo.toml`, and renamed `verify deps` to `verify` so some of it is me.

**Comment by Canop** [comment]
Let's close this one: I made a new one with almost no conflict.

**Pull request closed without merging**
